@host=http://localhost:8080

### Signup
POST /auth/signup
Content-Type: application/json
{
  "email": "test@testing.com",
  "password": "password"
}
?? status == 201

### Signin
# @name tokens
POST /auth/signin
Content-Type: application/json
{
  "email": "test@testing.com",
  "password": "password"
}
?? status == 200

### Ping
# @ref tokens
GET /ping
Authorization: Bearer {{tokens.data.access_token}}
?? status == 200

